spring:
  datasource:
    url: jdbc:dm://192.168.110.17:5236
    username: SYSDBA
    password: SYSDBA
    driver-class-name: dm.jdbc.driver.DmDriver


server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

or-tools:
  lib-paths:
    - "/or-tools/libortools.so.9"
    - "/or-tools/libjniortools.so"
#    - "/or-tools/jniortools.dll"

